name: azure-adf-cicd-project

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  # -------------------------
  # Build Job (Dev → Generate ARM templates)
  # -------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install ADF Utilities package
        run: npm install
        working-directory: ${{ github.workspace }}/build

      - name: Validate ADF resources
        run: npm run build validate ${{ github.workspace }}/ /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-dev-uksouth-cicd/providers/Microsoft.DataFactory/factories/df-dev-uksouth-cicd
        working-directory: ${{ github.workspace }}/build

      - name: Validate and Generate ARM template
        run: npm run build export ${{ github.workspace }}/ /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-dev-uksouth-cicd/providers/Microsoft.DataFactory/factories/df-dev-uksouth-cicd ExportedArmTemplate
        working-directory: ${{ github.workspace }}/build

      - name: Upload ARM template artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExportedArmTemplate
          path: ${{ github.workspace }}/build/ExportedArmTemplate

  # -------------------------
  # Deploy to Test
  # -------------------------
  release-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy to Test Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: rg-test-uksouth-cicd
          dataFactoryName: df-test-uksouth-cicd
          armTemplateFile: build/ExportedArmTemplate/ARMTemplateForFactory.json
          armTemplateParametersFile: parameters/test.parameters.json

  # -------------------------
  # Deploy to Prod (manual approval)
  # -------------------------
  release-prod:
    needs: release-test
    runs-on: ubuntu-latest
    environment: production   # 👈 triggers manual approval & uses environment secrets
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy to Prod Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: rg-prod-uksouth-cicd
          dataFactoryName: df-prod-uksouth-cicd
          armTemplateFile: build/ExportedArmTemplate/ARMTemplateForFactory.json
          armTemplateParametersFile: parameters/prod.parameters.json
