name: azure-adf-cicd-project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install ADF Utilities package
        run: npm install
        working-directory: ${{ github.workspace }}/build

      - name: Validate ADF resources
        run: npm run build -- validate ${{ github.workspace }}/ /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-dev-uksouth-cicd/providers/Microsoft.DataFactory/factories/df-dev-uksouth-cicd
        working-directory: ${{ github.workspace }}/build

      - name: Validate and Generate ARM template
        run: npm run build -- export ${{ github.workspace }}/ /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-dev-uksouth-cicd/providers/Microsoft.DataFactory/factories/df-dev-uksouth-cicd ExportedArmTemplate
        working-directory: ${{ github.workspace }}/build

      - name: Upload ARM template artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExportedArmTemplate
          path: ${{ github.workspace }}/build/ExportedArmTemplate

  release-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy to Data Factory (Test)
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: rg-test-uksouth-cicd
          dataFactoryName: df-test-uksouth-cicd
          armTemplateFile: ARMTemplateForFactory.json
          armTemplateParametersFile: ARMTemplateParametersForFactory.json
          additionalParameters: >
            ls_cicd_kv_properties_typeProperties_baseUrl=https://kv-df-test-uksouth-br.vault.azure.net/
            ls_az_sadl_kv_properties_typeProperties_url=https://sadltestuksouthbr.dfs.core.windows.net

  approve:
    needs: release-test
    runs-on: ubuntu-latest
    environment:
      name: Production   # 👈 Requires manual approval in GitHub Environments
    steps:
      - name: Wait for manual approval
        run: echo "✅ Approved to deploy to Production"

  release-prod:
    needs: approve
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy to Data Factory (Prod)
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: rg-prod-uksouth-cicd
          dataFactoryName: df-prod-uksouth-cicd
          armTemplateFile: ARMTemplateForFactory.json
          armTemplateParametersFile: ARMTemplateParametersForFactory.json
          additionalParameters: >
            ls_cicd_kv_properties_typeProperties_baseUrl=https://kv-df-prod-uksouth-br.vault.azure.net/
            ls_az_sadl_kv_properties_typeProperties_url=https://sadlproduksouth.dfs.core.windows.net
